### ISSUE TITLE
Request for dataset

### ISSUE THREAD

**Issue by mouad33** [ritvij-saxena/iris-detection-python#1]
hi Saxena, 

just I would like to ask if you could share the dataset used in this notebook

Thank you in advance.

**Comment by kunjal1309** [comment]
hello please give a\the dataset in this notbook

**Comment by ritvij-saxena** [comment]
I don't know if anyone still needs this dataset, but finally got the time to upload it. 

Here it is: [saxenaritvij/ritvij-saxena-iris-detection-python](https://huggingface.co/datasets/saxenaritvij/ritvij-saxena-iris-detection-python). 

Please do refer licenses before using it. Lastly, I do not intend to support this project anymore. Good luck!
